[build]
  # Build command - use Node 20 for compatibility
  command = "cd frontend && npm ci --legacy-peer-deps && npm run build"
  
  # Publish directory
  publish = "frontend/build"
  
  # Build context
  base = "/"
  
  # Environment variables for build
  [build.environment]
    NODE_VERSION = "20.11.0"
    NPM_VERSION = "10.2.4"
    CI = "true"
    GENERATE_SOURCEMAP = "false"
    REACT_APP_BACKEND_URL = "https://wedwallet.preview.emergentagent.com"

# SPA routing configuration
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API proxying (if needed in the future)
# [[redirects]]
#   from = "/api/*"
#   to = "https://wedwallet.preview.emergentagent.com/api/:splat"
#   status = 200
#   force = true