[build]
  # Build command
  command = "cd frontend && yarn install --legacy-peer-deps && yarn build"
  
  # Publish directory
  publish = "frontend/build"
  
  # Environment variables for build
  [build.environment]
    NODE_VERSION = "20.0.0"
    YARN_VERSION = "1.22.22"
    NPM_FLAGS = "--legacy-peer-deps"
    YARN_FLAGS = "--legacy-peer-deps"
    CI = "true"
    GENERATE_SOURCEMAP = "false"

# SPA routing configuration
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API proxying (if needed in the future)
# [[redirects]]
#   from = "/api/*"
#   to = "https://wedwallet.preview.emergentagent.com/api/:splat"
#   status = 200
#   force = true